name: sqlite_crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs) using Sqlite
version: 0.0.9+4
homepage: https://github.com/cachapa/sqlite_crdt
repository: https://github.com/cachapa/sqlite_crdt
issue_tracker: https://github.com/cachapa/sqlite_crdt/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  sqflite_common: ^2.4.3
  sqflite_common_ffi: ^2.2.3
  sqflite_common_ffi_web: ^0.3.4
  sql_crdt: ^0.0.9+1

dev_dependencies:
  lints: any
  test: any
  uuid: ^3.0.7
